### PR TITLE
Conditional sampling

### PR DESCRIPTION
**Pull request by mnwright**
Implements conditional sampling. 

This is the version started by @dswatson that we want to merge into main.

### CODE REVIEW

**Comment by mnwright** [comment]
It seems we have a problem with `alpha > 0`: 

````R
arf <- adversarial_rf(iris)
psi <- forde(arf, iris, alpha = 0.01)
# Error in psi_cat_fn(tree) :
# task 1 failed - "Elements listed in `by` must be valid column names in x and y"
````

This happens since this commit: d45cf14ffc891be340be56453cbcba27e101d4af

**Comment by dswatson** [comment]
I am unable to reproduce this error in the current version of this branch.

**Comment by mnwright** [comment]
Added a test and that also fails. I'll try to debug later.

**Comment by mnwright** [comment]
Should be fixed now.

**Pull request merged**
